name: build_on_rpi4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: rpi4
    steps:
      - uses: actions/checkout@v2
      - name: Build and install
        run: |
          make
          make install
