name: build_on_rpi4

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: rpi4
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          make
          make install
          (sleep 30; sudo reboot) &
