name: git_release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: rpi4

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make

      - name: Archive tar
        uses: actions/upload-artifact@v2
        with:
          name: pi_dash.tar.gz
          path: _build/prod/pi_dash-*
