# This is a basic workflow to help you get started with Actions

name: release

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: release
        run: |
          make